var testSentences = ["#companion_ger",
  "Hallo KRISTINA!",
  "Könntest du mir die Zeitung vorlesen?",
  "Könntest du den Artikel Das Entringer Freibad öffnete am Sonntag erstmals für einen Hundeschwimmtag vorlesen? ",
  "Nein, er war langweilig.",
  "Was gibt es denn heute für Veranstaltungen in der Stadt ?",
  "Was ist denn zur zeit populär in den sozialen Netzwerken ? ",
  "Ich würde gerne spazieren gehen .",
  "Ja, bitte.",
  "Ich möchte gerne rausgehen . ",
  "Danke für den Hinweis!",
  "Tschüss!",
  "#companion_tr",
  "Selam KRISTINA !",
  "Das Entringer Freibad öffnete am Sonntag erstmals für einen Hundeschwimmtag adlı makaleyi okur musun ?",
  "Evet , enteresandı .",
  "Sosyal medyada şu ara tartışılan konular ne ? ",
  "Bu akşam şehirdeki etkinliklere bakar mısın ?",
  "KRISTINA , bugün hava durumu nasıl ?",
  "Hah , yürüyüş için mükemmel .",
  "Sağol ! ",
  "Güle güle !",
  "#eat_ger",
  "Hallo KRISTINA!",
  "Hat Stefan Schlafprobleme ?",
  "Was kann ich tun , um ihm beim Einschlafen zu helfen ?",
  "Gibt es Tipps für einen besseren Schlaf ? ",
  "Wann geht er normalerweise ins Bett ? ",
  "Wann wacht er auf ?",
  "Weißt du , ob Stefan während  der Nacht aufwacht ?",
  "Braucht er irgendwelche Unterstützung , wenn er zur Toilette geht ? ",
  "Was macht er denn , nachdem er Fernsehen geschaut hat ? ",
  "Was ist sein Lieblingsbrettspiel ?",
  "Kennst du Stefan's Essgewohnheiten ?",
  "Was isst er gerne ?",
  "Kannst du mir ein paar Rezepte für Käsespätzle zeigen ",
  "Isst er Fleisch ? ",
  "Hat er irgendwelche Diätvorschriften ?",
  "Hat er irgendwelche anderen Krankeiten ?",
  "Kannst du mir bitte mehr Informationen über Demenz geben ?",
  "Was sind die üblichen Anzeichen und Symptome bei Demenz ?",
  "Gibt es für Demenz eine Therapie ?",
  "Gibt es praktische Regeln für Kommunikation mit Demenzkranken ? ",
  "Was ist der Unterschied zwischen Vergesslichkeit und Gedächtnisstörungen ?",
  "Kannst du mir allgemeine Informationen über Diabetes geben ? ",
  "Kannst du mir mehr Informationen über Diäten für Diabeteskranke geben ?",
  "Gibt es unterschiedliche Ernährungsempfehlungen für Diabetiker und Nichtdiabetiker ? ",
  "Wie steht es mit den Zeiten der Mahlzeiten bei Diabetes Typ 2 ?",
  "Sollten kohlenhydratreiche Lebensmittel aus dem Ernährungplan für Diabetiker ausgeschlossen werden ? ",
  "Kannst du mir ein paar Rezepte für Diabetes Typ 2 zeigen ?",
  "Danke für deine Unterstützung!",
  "Auf Wiedersehen!",
  "#eat_pl",
  "Witaj KRISTINO !",
  "Czy skarży się na trudności z zasypianiem ?",
  "Co mogę zrobić, żeby pomóc mu zasnąć ?",
  "O której godzinie się budzi ? ",
  "I jak długo Pan Stefan śpi podczas nocy ?",
  "Czy Pan Stefan potrzebuje pomocy kiedy chce iść do toalety?",
  "Czy możesz mi coś powiedzieć o zwyczajach żywieniowych Stefan ?",
  "Czy możesz mi pokazać parę przepisów na zacierki z serem po szwabsku ?",
  "Czy pije on alkohol ?",
  "Czy je on mięso ?",
  "Jakie ma alergie ?",
  "Czy ma problemy z pamięcią ?",
  "Chciałabym  otrzymać parę ogólnych informacji na temat demencji .",
  "Możesz mi coś powiedzieć o objawach i symptomach demencji ?",
  "Czy są jakieś możliwości terapeutyczne w przypadku demencji ?",
  "W jaki sposób różni się zanik pamięci w przypadku demencji Alzheimera od normalnego zapominania ?",
  "Czy są różnice w zaleceniach dietetycznych dla cukrzyków i nie-cukrzyków ?",
  "Czy osoby chore na cukrzycę mogą spożywać węglowodany w ramach diety ?",
  "Możesz mi pokazać parę przepisów na cukrzycę typu 2 ?",
  "Dziękuję za radę !",
  "Żegnaj KRISTINO !",
  "#babycare",
  "¡Buenas tardes KRISTINA!",
  "¿Qué es lo que determina el peso y la talla de un bebé recién nacido?",
  "¿Podrías facilitarme más información sobre el desarrollo físico de los bebés?",
  "¿Cuál es el peso medio de los bebés al nacer?",
  "¿Cuándo se considera que el bebé tiene bajo peso?",
  "Según los estándares internacionales, ¿cuáles son el peso y las medidas que debería tener mi bebé?",
  "¿Existen referencias internacionales sobre el crecimiento de los niños?",
  "¿Podrías darme más información sobre la lactancia materna?",
  "¿Cuál es la comida recomendada para los bebés durante los 6 primeros meses de vida?",
  "¿Cuál es la comida alternativa a la leche materna?",
  "¿Cuáles son los beneficios de la lactancia materna?",
  "¿Tendría que darle el pecho a mi bebé siempre que me lo pida?",
  "¿Cómo se regula la producción de leche durante la lactancia?",
  "¿Durante cuántos años se recomienda la lactancia materna?",
  "¿Es recomendable la lactancia materna de manera exclusiva?",
  "¿A partir de cuándo debería introducir otro tipo de comida para el bebé?",
  "¿Existe algun grupo de soporte donde poder preguntar más información sobre la lactancia?",
  "¿La vacunación es una medida preventiva a las enfermedades?",
  "Me gustaría saber algo más sobre la eficacia y la seguridad de las vacunas.",
  "¿Existen precauciones acerca de la vacunación?",
  "¿Existe un calendario para las vacunas?",
  "¿Cuáles son las vacunas más comúnmente empleadas?",
  "¿Las vacunas son gratuitas?",
  "¿Qué tendré que hacer en caso de una reacción inflamatoria?",
  "¿Podrías por favor facilitarme más información sobre las vacunas?",
  "Me gustaría dar un paseo con mi bebé.",
  "¿Podrías decirme qué tiempo hará hoy?",
  "¿Podrías por favor decirme dónde está el parque más cercano?",
  "¿Hay algun evento en el vecindario en el que pueda participar con mi bebé?",
  "Necesitaría más información sobre las revisiones médicas recomendadas para mi bebé.",
  "¿Cuánto tiempo tardarán en llegar los resultados de las revisiones recomendadas para mi bebé, según su edad?",
  "¿Cuáles son las revisiones pediátricas recomendadas para mi bebé?",
  "¿Qué es lo que tengo que hacer para poder tener una cita con mi pediatra?",
  "¿Cómo puedo obterner una cita con mi médico de familia?",
  "No tengo la tarjeta sanitaria. ¿Puedo pedir una cita con el médico?",
  "¿Por qué necesito una tarjeta sanitaria?",
  "¿Donde podría encontrar más información sobre la asistencia sanitaria a los inmigrantes?",
  "¿Cuál es el procedimiento para obtener el número de seguridad social en España?",
  "¿Existen algunos números de emergencia?",
  "¿Puedes encontrar los centros de salud más cercanos?",
  "De acuerdo, ¡muchas gracias!",
  "¡Hasta luego KRISTINA!",
  "#pain",
  "¡Hola KRISTINA!",
  "¿Podrías indicar cuáles son las causas que provocan el dolor de espalda?",
  "¿Podrías darme más información sobre el dolor de espalda?",
  "¿Qué se recomienda cuando una persona tiene dolor de espalda?",
  "¿Cuándo debería hablar con mi médico de familia sobre mi dolor de espalda?",
  "¿Cómo puedo obterner una cita con mi médico de familia?",
  "¿Por qué necesito una tarjeta sanitaria?",
  "Necesitaría más información sobre la asistencia sanitaria a los inmigrantes en España.",
  "¿Cuál es el procedimiento para obtener el número de seguridad social en España?",
  "¿A quién tengo que llamar en caso de emergencia?",
  "¿Puedes encontrar los centros de salud más cercanos?",
  "Perfecto, ¡gracias!",
  "¡Adiós KRISTINA!",
];